const countryList = {
    AED: ["AE", "United Arab Emirates"],
    AFN: ["AF", "Afghanistan"],
    XCD: ["AG", "Antigua and Barbuda"],
    ALL: ["AL", "Albania"],
    AMD: ["AM", "Armenia"],
    ANG: ["AN", "Netherlands Antilles"],
    AOA: ["AO", "Angola"],
    AQD: ["AQ", "Antarctica"],
    ARS: ["AR", "Argentina"],
    AUD: ["AU", "Australia"],
    AZN: ["AZ", "Azerbaijan"],
    BAM: ["BA", "Bosnia and Herzegovina"],
    BBD: ["BB", "Barbados"],
    BDT: ["BD", "Bangladesh"],
    XOF: ["BE", "Belgium"],
    BGN: ["BG", "Bulgaria"],
    BHD: ["BH", "Bahrain"],
    BIF: ["BI", "Burundi"],
    BMD: ["BM", "Bermuda"],
    BND: ["BN", "Brunei"],
    BOB: ["BO", "Bolivia"],
    BRL: ["BR", "Brazil"],
    BSD: ["BS", "Bahamas"],
    NOK: ["BV", "Bouvet Island"],
    BWP: ["BW", "Botswana"],
    BYR: ["BY", "Belarus"],
    BZD: ["BZ", "Belize"],
    CAD: ["CA", "Canada"],
    CDF: ["CD", "Congo (Kinshasa)"],
    XAF: ["CF", "Central African Republic"],
    CHF: ["CH", "Switzerland"],
    CLP: ["CL", "Chile"],
    CNY: ["CN", "China"],
    COP: ["CO", "Colombia"],
    CRC: ["CR", "Costa Rica"],
    CUP: ["CU", "Cuba"],
    CVE: ["CV", "Cape Verde"],
    CYP: ["CY", "Cyprus"],
    CZK: ["CZ", "Czechia"],
    DJF: ["DJ", "Djibouti"],
    DKK: ["DK", "Denmark"],
    DOP: ["DO", "Dominican Republic"],
    DZD: ["DZ", "Algeria"],
    ECS: ["EC", "Ecuador"],
    EEK: ["EE", "Estonia"],
    EGP: ["EG", "Egypt"],
    ETB: ["ET", "Ethiopia"],
    EUR: ["FR", "France"],
    FJD: ["FJ", "Fiji"],
    FKP: ["FK", "Falkland Islands"],
    GBP: ["GB", "United Kingdom"],
    GEL: ["GE", "Georgia"],
    GGP: ["GG", "Guernsey"],
    GHS: ["GH", "Ghana"],
    GIP: ["GI", "Gibraltar"],
    GMD: ["GM", "Gambia"],
    GNF: ["GN", "Guinea"],
    GTQ: ["GT", "Guatemala"],
    GYD: ["GY", "Guyana"],
    HKD: ["HK", "Hong Kong"],
    HNL: ["HN", "Honduras"],
    HRK: ["HR", "Croatia"],
    HTG: ["HT", "Haiti"],
    HUF: ["HU", "Hungary"],
    IDR: ["ID", "Indonesia"],
    ILS: ["IL", "Israel"],
    INR: ["IN", "India"],
    IQD: ["IQ", "Iraq"],
    IRR: ["IR", "Iran"],
    ISK: ["IS", "Iceland"],
    JMD: ["JM", "Jamaica"],
    JOD: ["JO", "Jordan"],
    JPY: ["JP", "Japan"],
    KES: ["KE", "Kenya"],
    KGS: ["KG", "Kyrgyzstan"],
    KHR: ["KH", "Cambodia"],
    KMF: ["KM", "Comoros"],
    KPW: ["KP", "North Korea"],
    KRW: ["KR", "South Korea"],
    KWD: ["KW", "Kuwait"],
    KYD: ["KY", "Cayman Islands"],
    KZT: ["KZ", "Kazakhstan"],
    LAK: ["LA", "Laos"],
    LBP: ["LB", "Lebanon"],
    LKR: ["LK", "Sri Lanka"],
    LRD: ["LR", "Liberia"],
    LSL: ["LS", "Lesotho"],
    LTL: ["LT", "Lithuania"],
    LVL: ["LV", "Latvia"],
    LYD: ["LY", "Libya"],
    MAD: ["MA", "Morocco"],
    MDL: ["MD", "Moldova"],
    MGA: ["MG", "Madagascar"],
    MKD: ["MK", "North Macedonia"],
    MMK: ["MM", "Myanmar"],
    MNT: ["MN", "Mongolia"],
    MOP: ["MO", "Macau"],
    MRO: ["MR", "Mauritania"],
    MTL: ["MT", "Malta"],
    MUR: ["MU", "Mauritius"],
    MVR: ["MV", "Maldives"],
    MWK: ["MW", "Malawi"],
    MXN: ["MX", "Mexico"],
    MYR: ["MY", "Malaysia"],
    MZN: ["MZ", "Mozambique"],
    NAD: ["NA", "Namibia"],
    XPF: ["NC", "New Caledonia"],
    NGN: ["NG", "Nigeria"],
    NIO: ["NI", "Nicaragua"],
    NPR: ["NP", "Nepal"],
    NZD: ["NZ", "New Zealand"],
    OMR: ["OM", "Oman"],
    PAB: ["PA", "Panama"],
    PEN: ["PE", "Peru"],
    PGK: ["PG", "Papua New Guinea"],
    PHP: ["PH", "Philippines"],
    PKR: ["PK", "Pakistan"],
    PLN: ["PL", "Poland"],
    PYG: ["PY", "Paraguay"],
    QAR: ["QA", "Qatar"],
    RON: ["RO", "Romania"],
    RSD: ["RS", "Serbia"],
    RUB: ["RU", "Russia"],
    RWF: ["RW", "Rwanda"],
    SAR: ["SA", "Saudi Arabia"],
    SBD: ["SB", "Solomon Islands"],
    SCR: ["SC", "Seychelles"],
    SDG: ["SD", "Sudan"],
    SEK: ["SE", "Sweden"],
    SGD: ["SG", "Singapore"],
    SKK: ["SK", "Slovakia"],
    SLL: ["SL", "Sierra Leone"],
    SOS: ["SO", "Somalia"],
    SRD: ["SR", "Suriname"],
    STD: ["ST", "Sao Tome and Principe"],
    SVC: ["SV", "El Salvador"],
    SYP: ["SY", "Syria"],
    SZL: ["SZ", "Eswatini"],
    THB: ["TH", "Thailand"],
    TJS: ["TJ", "Tajikistan"],
    TMT: ["TM", "Turkmenistan"],
    TND: ["TN", "Tunisia"],
    TOP: ["TO", "Tonga"],
    TRY: ["TR", "Turkey"],
    TTD: ["TT", "Trinidad and Tobago"],
    TWD: ["TW", "Taiwan"],
    TZS: ["TZ", "Tanzania"],
    UAH: ["UA", "Ukraine"],
    UGX: ["UG", "Uganda"],
    USD: ["US", "United States"],
    UYU: ["UY", "Uruguay"],
    UZS: ["UZ", "Uzbekistan"],
    VEF: ["VE", "Venezuela"],
    VND: ["VN", "Vietnam"],
    VUV: ["VU", "Vanuatu"],
    YER: ["YE", "Yemen"],
    ZAR: ["ZA", "South Africa"],
    ZMK: ["ZM", "Zambia"],
    ZWD: ["ZW", "Zimbabwe"]
  };


  // https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@2025.4.23/v1/currencies/usd.json
  // https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@2025.4.23/v1/currencies/USD.json


// const countryList = {

//     AED: "AE",
//     AFN: "AF",
//     XCD: "AG",
//     ALL: "AL",
//     AMD: "AM",
//     ANG: "AN",
//     AOA: "AO",
//     AQD: "AQ",
//     ARS: "AR",
//     AUD: "AU",
//     AZN: "AZ",
//     BAM: "BA",
//     BBD: "BB",
//     BDT: "BD",
//     XOF: "BE",
//     BGN: "BG",
//     BHD: "BH",
//     BIF: "BI",
//     BMD: "BM",
//     BND: "BN",
//     BOB: "BO",
//     BRL: "BR",
//     BSD: "BS",
//     NOK: "BV",
//     BWP: "BW",
//     BYR: "BY",
//     BZD: "BZ",
//     CAD: "CA",
//     CDF: "CD",
//     XAF: "CF",
//     CHF: "CH",
//     CLP: "CL",
//     CNY: "CN",
//     COP: "CO",
//     CRC: "CR",
//     CUP: "CU",
//     CVE: "CV",
//     CYP: "CY",
//     CZK: "CZ",
//     DJF: "DJ",
//     DKK: "DK",
//     DOP: "DO",
//     DZD: "DZ",
//     ECS: "EC",
//     EEK: "EE",
//     EGP: "EG",
//     ETB: "ET",
//     EUR: "FR",
//     FJD: "FJ",
//     FKP: "FK",
//     GBP: "GB",
//     GEL: "GE",
//     GGP: "GG",
//     GHS: "GH",
//     GIP: "GI",
//     GMD: "GM",
//     GNF: "GN",
//     GTQ: "GT",
//     GYD: "GY",
//     HKD: "HK",
//     HNL: "HN",
//     HRK: "HR",
//     HTG: "HT",
//     HUF: "HU",
//     IDR: "ID",
//     ILS: "IL",
//     INR: "IN",
//     IQD: "IQ",
//     IRR: "IR",
//     ISK: "IS",
//     JMD: "JM",
//     JOD: "JO",
//     JPY: "JP",
//     KES: "KE",
//     KGS: "KG",
//     KHR: "KH",
//     KMF: "KM",
//     KPW: "KP",
//     KRW: "KR",
//     KWD: "KW",
//     KYD: "KY",
//     KZT: "KZ",
//     LAK: "LA",
//     LBP: "LB",
//     LKR: "LK",
//     LRD: "LR",
//     LSL: "LS",
//     LTL: "LT",
//     LVL: "LV",
//     LYD: "LY",
//     MAD: "MA",
//     MDL: "MD",
//     MGA: "MG",
//     MKD: "MK",
//     MMK: "MM",
//     MNT: "MN",
//     MOP: "MO",
//     MRO: "MR",
//     MTL: "MT",
//     MUR: "MU",
//     MVR: "MV",
//     MWK: "MW",
//     MXN: "MX",
//     MYR: "MY",
//     MZN: "MZ",
//     NAD: "NA",
//     XPF: "NC",
//     NGN: "NG",
//     NIO: "NI",
//     NPR: "NP",
//     NZD: "NZ",
//     OMR: "OM",
//     PAB: "PA",
//     PEN: "PE",
//     PGK: "PG",
//     PHP: "PH",
//     PKR: "PK",
//     PLN: "PL",
//     PYG: "PY",
//     QAR: "QA",
//     RON: "RO",
//     RSD: "RS",
//     RUB: "RU",
//     RWF: "RW",
//     SAR: "SA",
//     SBD: "SB",
//     SCR: "SC",
//     SDG: "SD",
//     SEK: "SE",
//     SGD: "SG",
//     SKK: "SK",
//     SLL: "SL",
//     SOS: "SO",
//     SRD: "SR",
//     STD: "ST",
//     SVC: "SV",
//     SYP: "SY",
//     SZL: "SZ",
//     THB: "TH",
//     TJS: "TJ",
//     TMT: "TM",
//     TND: "TN",
//     TOP: "TO",
//     TRY: "TR",
//     TTD: "TT",
//     TWD: "TW",
//     TZS: "TZ",
//     UAH: "UA",
//     UGX: "UG",
//     USD: "US",
//     UYU: "UY",
//     UZS: "UZ",
//     VEF: "VE",
//     VND: "VN",
//     VUV: "VU",
//     YER: "YE",
//     ZAR: "ZA",
//     ZMK: "ZM",
//     ZWD: "ZW",
//   };